# Default values for deepfence-k8s-scanner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Management Console URL. Example: 22.33.44.55, deepfence.customer.com
managementConsoleUrl: ""
managementConsolePort: 443

# Auth: Get deepfence api key from UI -> Settings -> User Management
deepfenceKey: ""
createDeepfenceKeySecret: true

# Set custom name for the cluster and hostname prefix for agent vm's to easily identify in Deepfence UI.
# Example: prod-cluster or dev1-cluster
# It will be suffixed with hostname - prod-cluster-aks-agentpool-123456-vmss000001
clusterName: ""

image:
  repository: "deepfenceio/k8s-scanner"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"
  pullPolicy: Always

debug: true
replicaCount: 1

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

resources:
  requests:
    cpu: 150m
    memory: 50Mi
  limits:
    cpu: 1000m
    memory: 1Gi

nodeSelector: {"kubernetes.io/os": "linux"}

tolerations: []

affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "deepfence-k8s-scanner"

nameOverride: ""
fullnameOverride: ""