apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-scanner
  template:
    metadata:
      labels:
        name: k8s-scanner
    spec:
      containers:
        - name: k8s-scanner
          image: deepfenceio/k8s-scanner:latest
          imagePullPolicy: Always
          args:
            - -mgmt-console-url=142.93.216.241
            - -mgmt-console-port=443
            - -deepfence-key=2436a087-1925-4030-aa53-c28f73f858f4
            - -node-id=saurabh-agent-k8s
            - -debug=true
          securityContext:
            privileged: true
          ports:
            - containerPort: 80
      serviceAccountName: superreader